spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/security_playground
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
server:
  port: 18081